plugins {
    id 'java'
    id 'application'
}

group = 'by.bsuir.sdlc'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
}

application {
    mainClass = 'by.bsuir.sdlc.Main'
}

test {
    useJUnitPlatform()
}
